Add ReportsPage
HackerSchool/Arquimedia pull request #269
Opened 2022-08-11 13:11 UTC by LordOfTheNeverThere

This PR adds the Moderator Page that allows to see the Reports that have been made, along with each Report Relevant information.
It also fixes the Select UI problems we previously had.
Also adds 2 functions in utils, one for making array only have unique elements, another to retrieve what element appear the most times in an array.
Closes #240

2022-08-12 10:28 UTC, JeronimoMendes requested changes

2022-08-12 10:28 UTC, JeronimoMendes commented on frontend/src/components/report/ReportTableToolbar.js
> +		setTypes(uniqueTypes);
This variables should be constants

2022-08-12 10:28 UTC, JeronimoMendes commented on frontend/src/pages/ReportsPage.js
> +		console.log(reports);
Remove

2022-08-12 10:28 UTC, JeronimoMendes commented on frontend/src/pages/ReportsPage.js
> +				console.log(reports);
Remove

2022-08-24 12:39 UTC, LordOfTheNeverThere commented
@JeronimoMendes Just fixed the Problems

2022-08-24 12:50 UTC, JeronimoMendes approved these changes

2022-08-24 12:54 UTC, merged